ALTER TABLE "BusinessSettings"
ADD COLUMN "heroEyebrow" TEXT NOT NULL DEFAULT 'Lashed and Lifted',
ADD COLUMN "heroTitle" TEXT NOT NULL DEFAULT 'Lash design in motion.',
ADD COLUMN "heroSubtitle" TEXT NOT NULL DEFAULT 'A cinematic, luxury booking experience crafted for clients who want precision styling and seamless service.',
ADD COLUMN "scene2Eyebrow" TEXT NOT NULL DEFAULT 'Scene 2',
ADD COLUMN "scene2Title" TEXT NOT NULL DEFAULT 'Designed around your features.',
ADD COLUMN "scene2Description" TEXT NOT NULL DEFAULT 'Every appointment starts with personalized mapping so curl, density, and length complement your eyes-not overwhelm them.',
ADD COLUMN "scene3Eyebrow" TEXT NOT NULL DEFAULT 'Scene 3',
ADD COLUMN "scene3Title" TEXT NOT NULL DEFAULT 'Studio calm, editorial results.',
ADD COLUMN "scene3Description" TEXT NOT NULL DEFAULT 'From consultation to final mirror reveal, each step is paced for comfort while delivering camera-ready detail.',
ADD COLUMN "chapter1Title" TEXT NOT NULL DEFAULT 'Classic sets',
ADD COLUMN "chapter1Copy" TEXT NOT NULL DEFAULT 'Soft definition for an elegant everyday finish.',
ADD COLUMN "chapter2Title" TEXT NOT NULL DEFAULT 'Hybrid blends',
ADD COLUMN "chapter2Copy" TEXT NOT NULL DEFAULT 'The balance between texture and featherlight volume.',
ADD COLUMN "chapter3Title" TEXT NOT NULL DEFAULT 'Volume artistry',
ADD COLUMN "chapter3Copy" TEXT NOT NULL DEFAULT 'Full-bodied drama designed to still feel weightless.',
ADD COLUMN "chapter4Title" TEXT NOT NULL DEFAULT 'Refill rhythm',
ADD COLUMN "chapter4Copy" TEXT NOT NULL DEFAULT 'A maintenance cadence that keeps your look immaculate.',
ADD COLUMN "bookingCtaTitle" TEXT NOT NULL DEFAULT 'Ready for your next set?',
ADD COLUMN "bookingCtaBody" TEXT NOT NULL DEFAULT 'Reserve your appointment in minutes and we''ll guide you to the perfect service choice.',
ADD COLUMN "bookingCtaButtonLabel" TEXT NOT NULL DEFAULT 'Start booking';
